python3 -m salted.get_basis_info
python3 -m salted.initialize
python3 -m salted.sparse_selection
python3 -m salted.sparse_descriptor
python3 -m salted.rkhs_projector
python3 -m salted.rkhs_vector
python3 -m salted.hessian_matrix
python3 -m salted.solve_regression
python3 -m salted.validation
